id: A23BF9743
title: 'The Sage''s Powerful Words of Truth: A Prayer for the Spread of the Omniscient
  Buddha''s Teachings'
type: translation
pechas:
- I66163442
- I434A3A0F
- I9591DB96
- I580408A9
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:07:43.886171
  last_modified_at: 2023-01-04 12:07:43.886179
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I66163442/159D: E5F4
  I434A3A0F/8844: E5F4
  I9591DB96/134C: E5F4
  I580408A9/6A65: E5F4
